[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_plexer = "DcoHFXZHaLRQ2B37Bqc7afMpPr8T9VULyNdGj87wctcv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/datben/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
